.\" -*- mode: troff; coding: utf-8 -*-
.TH "mads-broker" "1" "2024/07/17"
.SH NAME
\fBmads-broker\fR - The broker for the MADS network
.SH SYNOPSIS
\fBmads-broker\fR [\fB-n, \[u2013]nic\fR] [\fB-s, \[u2013]settings\fR \fIarg\fR] [\fB-d, \[u2013]daemon\fR] [\fB-h, \[u2013]help\fR]
.SH DESCRIPTION
\fBmads-broker\fR is the broker for the MADS network. It is a server that listens for incoming connections from sources and sinks and routes messages between them. It also provides a centralized INI file for configurating each agent/client.
.SH OPTIONS
.IP "\fB-n\fR, \fB--nic\fR"
select the network interface (a string representing the nic name). This is purely cosmetic: the broker will listen on all interfaces anyway, but will use this nic name to identify the proper IP address and use it upon launch to provide the user with the correct IP address to be used for initializing the agents. Use \fB-n list\fR to list all available network interfaces.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fB-s\fR, \fB--settings\fR \fIarg\fR"
specify the settings file to be used. If not specified, the default settings file is used (usually /usr/local/etc/mads.ini).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fB-d\fR, \fB--daemon\fR"
run the broker as a daemon. This suppress the output to the console upon launch and the interactive behavior.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fB-h\fR, \fB--help\fR"
show summary of options.
.SH BUGS
The upstream bug tracker can be found at \fIhttps://github.com/pbosetti/MADS/issues\fR.
.SH SEE ALSO
\fBmads\fR(1), \fBmads-logger\fR(1), \fBmads-source\fR(1), \fBmads-sink\fR(1), \fBmads-filter\fR(1)
.SH FILES
\fB/usr/local/etc/mads.ini\fR: MADS configuration file.
.SH AUTHOR
\fBmads-broker\fR was written by Paolo Bosetti \fIpaolo.bosetti@unitn.it\fR.
