.\" -*- mode: troff; coding: utf-8 -*-
.TH "mads-filter" "1" "2024/07/17"
.SH NAME
\fBmads-filter\fR - The filter agent for the MADS network
.SH SYNOPSIS
\fBmads-filter\fR 
[\fB-n, --name\fR \fIagent_name\fR] 
[\fB-i, --agent-id\fR \fIagent-id\fR]
[\fB-s, --settings\fR \fIURI\fR]
[\fB-S, --save-settings\fR \fIfilename\fR]
[\fB-h, --help\fR]
[\fIplugin\fR]
.SH DESCRIPTION
\fBmads-filter\fR is the filter agent for the MADS network. 
.SH ARGUMENTS
.IP "\fIplugin\fR"
The plugin to be loaded. The plugin is a shared library (with the \fB.plugin\fR extension) that implements the filter agent. You must provide either a full path to the plugin or the plugin name (without extension) if the plugin is in the standard plugin directory (/usr/local/lib/).
.SH OPTIONS
.IP "\fB-n\fR, \fB--name\fR"
The agent name. By default, the agent name is the plugin file name, without extension, so the plugin \fBpublish.plugin\fR will have the agent name \fBpublish\fR. The agent name is used for fetching the proper section forom the INI file, so this option allows to have different settings for different filter agents loading the same plugin.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fB-i\fR, \fB--agent-id\fR"
The agent_id field is appended to the message payload. It allows to mark different agents that share the same agent name and the same settings section.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fB-s\fR, \fB--settings\fR \fIURI\fR"
Path to the settings file (ini format). It can be a valid ZeroMQ url in the form tcp://host:port.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fB-S\fR, \fB--save-settings\fR \fIfilename\fR"
Save the settings (loaded by the broker or via \fB-s\fR option) to the given file (ini format).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fB-h\fR, \fB--help\fR"
show summary of options.
.SH DEFAULT PLUGIN
The default plugin (if omitted) is \fBbridge.plugin\fR. This plugin prints to standard output any message received from the broker, then listens for messages on standard input and sends them back to the broker. This allows to use the filter agent as a simple command line tool to prototype a filter agent, typically by piping stdin and stdout to a scripting language.
.SS EXAMPLE SCRIPT (in Python3)
An example of using the default plugin and piping \fBmads-filter\fR via Python3 would be:
.LP
.EX
  #!/usr/bin/env python3
  import subprocess
  import json

  command = \(dq./products/bin/mads-filter\(dq
  process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, stdin=subprocess.PIPE, shell=True)

  while True:
    # read input from the agent
    json_input = json.loads(process.stdout.readline())
    # change the input somehow
    json_input[\(dqreply\(dq] = True
    # Dump the json as string
    json_str = json.dumps(json_input, separators=(',', ':'))
    print(json_str)
    # write the json to the agent stdin (convert to bytes and append \en)
    process.stdin.write(json_str.encode('UTF-8') + b'\en')
    process.stdin.flush()
.EE
.SH BUGS
The upstream bug tracker can be found at \fIhttps://github.com/pbosetti/MADS/issues\fR.
.SH SEE ALSO
\fBmads\fR(1), \fBmads-broker\fR(1), \fBmads-logger\fR(1), \fBmads-sink\fR(1), \fBmads-source\fR(1)
.SH FILES
\fB/usr/local/etc/mads.ini\fR: MADS configuration file.
.SH AUTHOR
\fBmads-filter\fR was written by Paolo Bosetti \fIpaolo.bosetti@unitn.it\fR.
