.\" -*- mode: troff; coding: utf-8 -*-
.TH "mads" "1" "2024/07/17"
.SH NAME
\fBmads\fR - frontend wrapper to MADS command line tools
.SH SYNOPSIS
\fBmads\fR [\fB-h|\[u2013]help\fR] \fIsubcommand\fR [\fIargs\fR]
.SH DESCRIPTION
\fBmads\fR is a simple wrapper to the MADS command line tools. It just makes the syntax nicer, allowing you to call e.g. mads broker rather than mads-broker.
.PP
In addition, the \fBmads\fR command allows to create systemd services for running MADS agents as services. The services are created in the /etc/systemd/system directory and can be started, stopped, enabled and disabled using the systemctl command.
.SH OPTIONS
.IP "\fB-h\fR, \fB--help\fR"
Show summary of options.
.SH SUBCOMMANDS
\fBmads\fR supports the following subcommands:
.IP "\fBbroker\fR"
Start a MADS broker. Use -d option unless you want it interactive. Wraps \fBmads-broker\fR.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fBlogger\fR"
Start a MADS logger. Wraps \fBmads-logger\fR.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fBsource\fR"
Start a MADS source. Wraps \fBmads-source\fR.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fBsink\fR"
Start a MADS sink. Wraps \fBmads-sink\fR.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fBfilter\fR"
Start a MADS filter. Wraps \fBmads-filter\fR.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fBservice\fR"
Create a systemd service for a MADS agent. The service is created in /etc/systemd/system and can be started, stopped, enabled and disabled using the systemctl command. See below for more details.
.SS SERVICE SUBCOMMAND
The \fBservice\fR subcommand has the following syntax:
.PP
\fBmads\fR \fBservice\fR \fIservice_name\fR \fIcommand\fR [\fIargs\fR]
.PP
where \fIcommand\fR is one of \fBbroker\fR, \fBlogger\fR, \fBsource\fR, \fBsink\fR or \fBfilter\fR and \fIname\fR is the name of the service to be created. The \fIargs\fR are the arguments to be passed to the agent.
.PP
This command prints to the console the content of a systemd service file. Inspcet it to check if it is correct, then re-issue the same command with \fBsudo\fR to actually create the service.
.PP
Then, use \fBsystemctl start\fR \fIservice_name\fR to start the service, \fBsystemctl stop\fR \fIservice_name\fR to stop it, \fBsystemctl enable\fR \fIservice_name\fR to enable it at boot time and \fBsystemctl disable\fR \fIservice_name\fR to disable it.
.SH BUGS
The upstream bug tracker can be found at \fIhttps://github.com/pbosetti/MADS/issues\fR.
.SH SEE ALSO
\fBmads-broker\fR(1), \fBmads-logger\fR(1), \fBmads-source\fR(1), \fBmads-sink\fR(1), \fBmads-filter\fR(1)
.SH FILES
\fB/etc/systemd/system/mads-.service\fR: systemd service files created by \fBmads service\fR.
.PP
\fB/usr/local/etc/mads.ini\fR: MADS configuration file.
.SH AUTHOR
\fBmads\fR was written by Paolo Bosetti \fIpaolo.bosetti@unitn.it\fR.
