.\" -*- mode: troff; coding: utf-8 -*-
.TH "mads-logger" "1" "2024/07/17"
.SH NAME
\fBmads-logger\fR - The logger for the MADS network
.SH SYNOPSIS
\fBmads-logger\fR 
[\fB-p, --pause\fR] 
[\fB-e, --echo\fR]
[\fB-n, --no-mongo\fR]
[\fB-m, --mongo\fR \fIURI\fR]
[\fB-f, --file\fR \fIfilename\fR]
[\fB-a, --array\fR]
[\fB-x, --cross\fR]
[\fB-s, --settings\fR \fIarg\fR]
[\fB-S, --save-settings\fR \fIarg\fR]
[\fB-h, --help\fR]
.SH DESCRIPTION
\fBmads-logger\fR is the logger for the MADS network. It is monolithinc agent that listens for incoming messages from sources and sinks and logs them to a file or to a MongoDB database. The logger can be configured to pause the logging, to echo the incoming messages to the console, to log to a file or to a MongoDB database.
.SH OPTIONS
.IP "\fB-p\fR, \fB--pause\fR"
Start the logger paused. The logger will not log any message until the pause is lifted, typicaly by using the \fBresume\fR command on the GUI or by sending a {\(dqpause\[u201D]: false} message to the metadata topic. The message {\(dqpause\[u201D]: true} stops the logging
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fB-e\fR, \fB--echo\fR"
echoes to the console any logged message.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fB-n\fR, \fB--no-mongo\fR"
Disable logging to the MongoDB database, only logs to a file if \fB-f\fR \fIfilename\fR is given.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fB-m\fR, \fB--mongo\fR \fIURI\fR"
Log to the MongoDB database at the given URI. The URI must be in the form mongodb://user:password@host:port. If the URI is not given, the default URI mongodb://localhost:27017 is used.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fB-f\fR, \fB--file\fR \fIfilename\fR"
Log to the given file. If the file exists, the logger appends to it. If the file does not exist, the logger creates it.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fB-a\fR, \fB--array\fR"
Log to a file as an array of JSON objects. If not, each message is logged as a separate JSON object, one per line.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fB-x\fR, \fB--cross\fR"
Cross-connect sockets: this is for debugging purposes and allows to connect an agent directly to the logger, bypassing the broker. For this to work, the logger agent needs to read a local settings file (\fB-s\fR option).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fB-s\fR, \fB--settings\fR \fIURI\fR"
Path to the settings file (ini format). It can be a valid ZeroMQ url in the form tcp://host:port.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fB-S\fR, \fB--save-settings\fR \fIfilename.ini\fR"
Save the settings (loaded by the broker or via \fB-s\fR option) to the given file (ini format).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\fB-h\fR, \fB--help\fR"
show summary of options.
.SH BUGS
The upstream bug tracker can be found at \fIhttps://github.com/pbosetti/MADS/issues\fR.
.SH SEE ALSO
\fBmads\fR(1), \fBmads-broker\fR(1), \fBmads-source\fR(1), \fBmads-sink\fR(1), \fBmads-filter\fR(1)
.SH FILES
\fB/usr/local/etc/mads.ini\fR: MADS configuration file.
.SH AUTHOR
\fBmads-logger\fR was written by Paolo Bosetti \fIpaolo.bosetti@unitn.it\fR.
