FROM ubuntu:24.04
LABEL org.opencontainers.image.authors="paolo.bosetti@unitn.it"
ARG DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC

ARG BUILDDIR=/build

RUN mkdir ${BUILDDIR}
WORKDIR /root

RUN apt-get update && apt-get install -y \
    clang \
    cmake \
    libssl-dev \
    git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* 

COPY src ${BUILDDIR}/src
COPY CMakeLists.txt ${BUILDDIR}
COPY external.cmake ${BUILDDIR}
COPY Dockerfile.in ${BUILDDIR}
COPY mads.ini ${BUILDDIR}
COPY share ${BUILDDIR}/share
COPY scripts ${BUILDDIR}/scripts

ENV CC=/usr/bin/clang
ENV CXX=/usr/bin/clang++

RUN cd ${BUILDDIR} && \
    cmake -Bbuild -DMADS_ENABLE_METADATA=OFF -DMADS_ENABLE_LOGGER=ON -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build -j6 && \
    cmake --install build --prefix /usr/local && \
    rm -rf build && \
    cp ${BUILDDIR}/products/lib/*.so* /usr/local/lib

EXPOSE 9090 9091 9092

LABEL version=@LIB_VERSION@

ENTRYPOINT ["/usr/local/bin/mads"]
CMD ["broker"]