/*
  __  __                         ____            _                  
 |  \/  | ___  _ __   __ _  ___ |  _ \ ___ _ __ | | __ _ _   _      
 | |\/| |/ _ \| '_ \ / _` |/ _ \| |_) / _ \ '_ \| |/ _` | | | |     
 | |  | | (_) | | | | (_| | (_) |  _ <  __/ |_) | | (_| | |_| |     
 |_|  |_|\___/|_| |_|\__, |\___/|_| \_\___| .__/|_|\__,_|\__, |     
                     |___/                |_|            |___/      
# A source plugin that replays MongoDB collections
# Generated by the command: plugin -t source mongo_replay -d mongo_replay_plugin
# Hostname: Fram-IV.local
# Current working directory: /Users/p4010/Develop/MADS_plugins
# Creation date: 2026-03-10T13:10:09.176+0100
# NOTICE: MADS Version 2.0.0
*/
// Mandatory included headers
#include <source.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>
#include <thread>
#include <chrono>
#include "../mongo_fetch.hpp"
#include <mongocxx/exception/query_exception.hpp>

// other includes as needed here

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "replay"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class Mongo_replayPlugin : public Source<json> {

public:

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: the result is published
  // return_type::retry: go to next loop, nothing is published
  // return_type::warning: content of _error is added to result befor publishing
  // return_type::error: the result only has a copy of _error
  // return_type::critical: execution stops
  return_type get_output(json &out, vector<unsigned char> *blob = nullptr) override {
    out.clear();
    if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    string collection_name;
    next_loop_duration = _fetcher->load_next(out, collection_name);
    if (next_loop_duration.count() < 0) {
      cout << endl << "No more data to replay." << endl;
      return return_type::critical;
    }
    out["topic"] = collection_name;
    if (_max_loop_duration > 0ms && next_loop_duration > _max_loop_duration) {
      next_loop_duration = _max_loop_duration;
    }
    return return_type::success;
  }

  void set_params(const json &params) override {
    Source::set_params(params);
    _params["db_uri"] = "mongodb://localhost:27017/";
    _params["unwrap_original"] = false;
    _params["unroll_timestamp"] = false;
    _params.merge_patch(params);
    try {
      _fetcher = make_unique<Mads::MongoFetch>(_params["db_uri"].get<string>());
      _fetcher->connect();
    } catch (const mongocxx::query_exception &e) {
      cout << "Error connecting to MongoDB: " << e.what() << endl;
      exit(EXIT_FAILURE);
    } catch (const std::exception &e) {
      cout << "Error initializing MongoFetch: " << e.what() << endl;
      exit(EXIT_FAILURE);
    }
    if (!_params.contains("db_name") || !_params["db_name"].is_string()) {
      throw std::runtime_error("Missing or invalid `db_name` parameter: expected a string.");
    }
    _fetcher->select_database(_params["db_name"]);
    if (_params.contains("collections")) {
      if (!_params["collections"].is_array()) {
        throw std::runtime_error("Invalid `collections` parameter: expected an array of strings.");
      }
      vector<string> collections;
      for (const auto &item : _params["collections"]) {
        if (!item.is_string()) {
          throw std::runtime_error("Invalid `collections` parameter: expected an array of strings.");
        }
        collections.push_back(item.get<string>());
      }
      _fetcher->select_collections(collections);
    } else {
      throw std::runtime_error("Missing `collections` parameter.");
    }
    try {
      if (_params.contains("start_time") && _params["start_time"].is_string()) {
        if (_params.contains("end_time") && _params["end_time"].is_string()) {
          _fetcher->select_time_range(_params["start_time"], _params["end_time"]);
        } else {
          _fetcher->select_time_range(_params["start_time"]);
        }
      }
    } catch (const std::exception &e) {
      throw std::runtime_error(string("Invalid time range: ") + e.what());
    }
    _max_loop_duration = std::chrono::milliseconds(_params.value("max_loop_duration_ms", 0));
    _fetcher->set_repeat(_params.value("repeat", false));
    try {
      if (_params.value("reuse_view", false)) {
        _fetched_records = _fetcher->fetch_data_from(_params.value("view_name", ""));
      } else {
        _fetched_records = _fetcher->fetch_data(_params.value("view_name", ""));
      }
    } catch (const mongocxx::query_exception &e) {
      cout << "Error fetching data from MongoDB: " << e.what() << endl;
      exit(EXIT_FAILURE);
    } catch (const std::exception &e) {
      cout << "Unexpected error: " << e.what() << endl;
      exit(EXIT_FAILURE);
    }

    _fetcher->set_unwrap_original(_params.value("unwrap_original", false));
  }

  map<string, string> info() override {     
    return {
      {"Records", to_string(_fetched_records)},
      {"Database URI", _params.value("db_uri", "N/A")},
      {"Database Name", _params.value("db_name", "N/A")},
      {"Collections", _params["collections"].dump()},
      {"Time Range", _params.value("start_time", "N/A") + " to " + _params.value("end_time", "now")},
      {"Repeat", _repeat ? "Yes" : "No"},
      {"Max Loop Dur. ms", to_string(_max_loop_duration.count())},
      {"View Name", _params.value("view_name", "")},
      {"Reuse View", _params.value("reuse_view", false) ? "Yes" : "No"}
    };
    
  };

private:
  unique_ptr<Mads::MongoFetch> _fetcher;
  std::size_t _fetched_records{0};
  std::chrono::milliseconds _max_loop_duration{0}; // Set a default maximum loop duration of 1 second
  bool _repeat{false}; // Whether to repeat the replay when all data has been processed
};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_SOURCE_DRIVER(Mongo_replayPlugin, json)


/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/
int main(int argc, char const *argv[]) {
  Mongo_replayPlugin plugin;
  json output, params;

  // Set example values to params
  params["db_uri"] = "mongodb://jakku.dii.unitn.it:27017/";
  params["db_name"] = "miroscic";
  params["collections"] = {"arduino_dashboard", "hpe_out"};
  params["start_time"] = "2025-01-01T00:00:00Z";
  params["max_loop_duration_ms"] = 1000;
  
  // Set the parameters
  plugin.set_params(params);

  for (const auto &item : plugin.info()) {
    cout << item.first << ": " << item.second << endl;
  }
  
  // Process data
  for (size_t i = 0; i < 10; i++) {
    plugin.get_output(output);
    cout << "Output: " << output.dump() << endl;
    cout << "Next loop in: " << plugin.next_loop_duration.count() << " ms" << endl;
  }

  // Produce output
  cout << "Output: " << output << endl;

  return 0;
}
