// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// goertzelCore
SEXP goertzelCore(SEXP a, SEXP alpha);
RcppExport SEXP fdmethods_goertzelCore(SEXP aSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type alpha(alphaSEXP);
    __result = Rcpp::wrap(goertzelCore(a, alpha));
    return __result;
END_RCPP
}
