# A Template for {{class_name}}, a {{type}} Plugin
# Generated by the command: {{cli}}
# Hostname: {{hostname}}
# Current working directory: {{cwd}}
# Creation date: {{today}}
# NOTICE: MADS Version {{mads_version}}