#!/bin/bash
#   __  __    _    ____  ____                                             
#  |  \/  |  / \  |  _ \/ ___|  __      ___ __ __ _ _ __  _ __   ___ _ __ 
#  | |\/| | / _ \ | | | \___ \  \ \ /\ / / '__/ _` | '_ \| '_ \ / _ \ '__|
#  | |  | |/ ___ \| |_| |___) |  \ V  V /| | | (_| | |_) | |_) |  __/ |   
#  |_|  |_/_/   \_\____/|____/    \_/\_/ |_|  \__,_| .__/| .__/ \___|_|   
#                                                  |_|   |_|              
# MADS wraper for all "mads-" prefixed commands
CMD_PREFIX="mads-"
AVAILABLE_COMMANDS=("broker" "logger" "source" "filter" "sink" "feedback", "dealer" "worker" "command" "logging" "plugin")
USR_PATH="$(dirname "$(dirname "$(readlink -f "$0")")")"
SYSTEMD_PATH="/etc/systemd/system"

# Define the usage function
usage() {
  echo "Usage: $0 <command> [arguments...]"
  echo "Available commands:"
  for command in "${AVAILABLE_COMMANDS[@]}"; do
    if [ -f "${USR_PATH}/bin/${CMD_PREFIX}${command}" ]; then
      echo "  - $command"
    fi
  done
  if [ "$(uname)" == "Linux" ]; then
    echo "  - service <service_name> <command> [arguments...]"
  fi
  echo "type mads <command> -h for command help"
}

# Define the function to print a systemd service file
print_service_file() {
  # Check if the number of arguments is 0
  if [ $# -lt 3 ]; then
    echo "No command provided."
    usage
    exit 1
  fi
  local name=$2
  local description="$3"
  shift 2
  local command="${CMD_PREFIX}$@"
  local out_stream="/dev/stdout"
  if [ "$(id -u)" = "0" ]; then
    out_stream=${SYSTEMD_PATH}/${CMD_PREFIX}${name}.service
    echo "Running as root; saving service file to ${out_stream}"
  fi

  cat <<EOF > ${out_stream}
#  __  __    _    ____  ____  
# |  \/  |  / \  |  _ \/ ___| 
# | |\/| | / _ \ | | | \___ \ 
# | |  | |/ ___ \| |_| |___) |
# |_|  |_/_/   \_\____/|____/ 
#
# Linux Systemd service file for MADS ${description}
# Notice that the settings file will be read from 
# ${USR_PATH}/etc/mads.ini
#
# Save this file to ${SYSTEMD_PATH}/${CMD_PREFIX}${name}.service
# (or run "sudo mads service ${name} $@" 
# to save it automatically)
# then run "sudo systemctl enable ${CMD_PREFIX}${name}.service"

[Unit]
Description=MADS ${name}
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=${USER}
ExecStart=${USR_PATH}/bin/${command}

[Install]
WantedBy=multi-user.target
EOF
}

if [ "$1" = "-v" ] || [ "$1" = "--version" ]; then
  mads-broker -v
  exit 0
fi

# Check if the program argument is provided
if [ -z "$1" ]; then
  usage
  exit 1
fi


# Check if the operating system is Linux
if [ "$(uname)" == "Linux" ]; then
  # Check if the program argument is the "service" command
  if [ "$1" = "service" ]; then
    # Call the function for the "service" command
    print_service_file "$@"
    exit 0
  fi
fi

# Check if the program argument is a valid command
if [[ ! " ${AVAILABLE_COMMANDS[@]} " =~ " $1 " ]]; then
  echo "Invalid command: $1"
  usage
  exit 1
fi

# Store the program name
PROGRAM=$CMD_PREFIX"$1"

# Shift the arguments to remove the program name
shift

# Call the program with the remaining arguments
${PROGRAM} "$@"