/*
  __  __                         _____    _       _     
 |  \/  | ___  _ __   __ _  ___ |  ___|__| |_ ___| |__  
 | |\/| |/ _ \| '_ \ / _` |/ _ \| |_ / _ \ __/ __| '_ \ 
 | |  | | (_) | | | | (_| | (_) |  _|  __/ || (__| | | |
 |_|  |_|\___/|_| |_|\__, |\___/|_|  \___|\__\___|_| |_|
                     |___/                              
Paolo Bosetti, 2026
Fetches data from multiple MongoDB collections and prepare for replay by 
merging them into a single view sorted by timestamp, also providing the time 
difference between records.
*/
#pragma once

#include <chrono>
#include <optional>
#include <string>
#include <vector>

#include <bsoncxx/document/value.hpp>
#include <mongocxx/client.hpp>
#include <mongocxx/database.hpp>
#include <mongocxx/uri.hpp>
#include <mongocxx/cursor.hpp>
#include <nlohmann/json.hpp>

namespace Mads {

class MongoFetch {
public:
  /**
   * @brief Construct a fetcher bound to the specified MongoDB URI.
   * @param uri MongoDB connection URI used when `connect()` is called.
   */
  explicit MongoFetch(const std::string &uri);

  /**
   * @brief Destroy the fetcher instance.
   *
   * If still connected, this calls `disconnect()` to release the connection and clean up any
   * owned temporary replay view.
   */
  ~MongoFetch();

  /**
   * @brief Open the connection to the MongoDB server.
   */
  void connect();

  /**
   * @brief Close the connection to the MongoDB server and clear replay state.
   *
   * If the active replay view was auto-generated by `fetch_data()`, it is dropped from the
   * database before the connection is closed.
   */
  void disconnect();

  /**
   * @brief Select the database on which to operate.
   * @param db_name Database name to use for subsequent operations.
   */
  void select_database(const std::string &db_name);

  /**
   * @brief Define the list of collections to fetch data from.
   * @param collections Collection names to merge into the replay view.
   */
  void select_collections(const std::vector<std::string> &collections);

  /**
   * @brief Select the time range of interest.
   * @param start Inclusive lower bound, expressed as epoch milliseconds or ISO-8601 UTC string.
   * @param end Inclusive upper bound, expressed as epoch milliseconds or ISO-8601 UTC string.
   */
  void select_time_range(const std::string &start, const std::string &end);

  /**
   * @brief Select the time range of interest, using the current time as the end of the period.
   * @param start Inclusive lower bound, expressed as epoch milliseconds or ISO-8601 UTC string.
   */
  void select_time_range(const std::string &start);

  /**
   * @brief Create a replay view over the selected MongoDB data.
   *
   * The resulting view has a temporary random name and is deleted automatically on disconnect
   * or object destruction.
   * Each record in the view is represented as a JSON object with these fields:
   * - `timestamp`: the record timestamp as a BSON UTC date
   * - `collection_name`: the name of the source collection
   * - `data`: the original BSON document
   *
   * Records are sorted by timestamp and filtered using the time range selected with
   * `select_time_range()`.
   *
   * @return Number of documents exposed by the created replay view.
   */
  std::size_t fetch_data();

  /**
   * @brief Create a replay view over the selected MongoDB data.
   *
   * The resulting view has a temporary random name, unless `view_name` already contains one.
   * If a name is provided, the view remains in the database after disconnect or object
   * destruction.
   * Each record in the view is represented as a JSON object with these fields:
   * - `timestamp`: the record timestamp as a BSON UTC date
   * - `collection_name`: the name of the source collection
   * - `data`: the original BSON document
   *
   * Records are sorted by timestamp and filtered using the time range selected with
   * `select_time_range()`.
   *
   * @param view_name Optional caller-provided name for the generated view. If empty, a name is generated and written back.
   * @return Number of documents exposed by the created replay view.
   */
  std::size_t fetch_data(std::string &view_name);

  /**
   * @brief Create a persistent replay view with the specified name.
   *
   * The view is created on the server and is not deleted automatically on object destruction
   * or disconnect.
   *
   * @param view_name Name of the server-side replay view to create or replace.
   * @return Number of documents exposed by the created replay view.
   */
  std::size_t fetch_data(const std::string &view_name);

  /**
   * @brief Reuse an existing persistent replay view.
   *
   * The named server-side object must exist, must be a MongoDB view, and must expose replay rows
   * compatible with `load_next()`.
   *
   * @param view_name Name of the existing replay view to attach to.
   * @return Number of documents exposed by the reused view.
   */
  std::size_t fetch_data_from(const std::string &view_name);

  /**
   * @brief Set whether replay restarts from the beginning after the last record.
   * @param repeat If `true`, `load_next()` loops over the replay view; otherwise it stops at the end.
   */
  void set_repeat(bool repeat) { _repeat = repeat; }

  /**
   * @brief Load the next record from the replay view.
   *
   * Only the `data` field of the current record is loaded into `out`, while `collection_name`
   * receives the originating collection name.
   *
   * @param out JSON object populated with the next record payload.
   * @param collection_name Output string receiving the source collection name.
   * @return Delay before loading the following record, or a negative duration when no more data are available.
   */
  std::chrono::milliseconds load_next(nlohmann::json &out, std::string &collection_name);

  /**
   * @brief Set whether to unwrap the original document.
   * @param unwrap If `true`, the original document is unwrapped; otherwise, 
   * it is kept as a nested object.
   */

  void set_unwrap_original(bool unwrap) { _unwrap_original = unwrap; }


private:
  struct ReplayRow {
    std::chrono::milliseconds timestamp{0};
    std::string collection_name;
    nlohmann::json data;
  };

  std::size_t activate_view(const std::string &view_name, bool owns_view);
  void reset_replay_stream();
  void validate_replay_view(mongocxx::database &database, const std::string &view_name) const;
  void drop_owned_view() noexcept;

  std::string _uri_string;
  mongocxx::uri _uri;
  std::optional<mongocxx::client> _client;
  std::string _database_name;
  std::vector<std::string> _collections;
  std::optional<std::chrono::milliseconds> _start_time;
  std::optional<std::chrono::milliseconds> _end_time;
  std::string _view_name;
  bool _owns_view{false};
  std::size_t _view_size{0};
  std::size_t _next_index{0};
  bool _repeat{false};
  std::optional<mongocxx::cursor> _cursor;
  std::optional<mongocxx::cursor::iterator> _cursor_it;
  std::optional<ReplayRow> _next_row;

  bool _unwrap_original{false};
};

}  // namespace Mads
